# 基于nginx:alpine镜像的ibas镜像
# OS：alpine
FROM nginx:alpine

# 作者
MAINTAINER zhanhaibin 

# 安装工具
RUN set -x \
# 更新源
    && apk update \
# 安装解压、网络请求
    && apk add --no-cache curl wget unzip \
# 删除源
    && rm -rf /var/cache/apk/*

# 定义环境变量
ENV \
    # nginx目录
    NGINX_HOME=/usr/share/nginx \
    NGINX_CONFIG=/etc/nginx/ 

# 部署ibas程序
RUN set -x \
    # 初始化环境
    && mkdir -p "${NGINX_HOME}"/apps/ \
    && mkdir -p "${NGINX_CONFIG}"/cert/ \
    && mkdir -p "${NGINX_CONFIG}"/logs/ 

# 拷贝配置文件
COPY "/srv/ibas/nginx-proxy/apps" \
    "index.html" \
    "${NGINX_HOME}"/html/ 

COPY "/srv/ibas/nginx-proxy/cert" \
    "nginx.conf" \
    "${NGINX_CONFIG}" 
    
# 设置工作目录
WORKDIR "${NGINX_HOME}"