# 基于nginx镜像的ibas镜像
# OS：alpine
FROM alpine:Latest

# 作者
MAINTAINER Niuren.Zhu "niuren.zhu@icloud.com"

# 定义环境变量
ENV \
# ibas目录
    IBAS_HOME=/home/ \
# ibas-data
    IBAS_DATA=/home/ibas/ 

# 初始化环境
RUN mkdir -p "${IBAS_DATA}";


# 安装工具
RUN set -x \
    # 更新源
    && apk update \
    # 安装解压、网络请求
    && apk add --no-cache curl wget unzip vim \
    # 删除源
    && rm -rf /var/cache/apk/*

# 设置工作目录
WORKDIR "${NGINX_HOME}"
