# 基于nginx镜像的ibas镜像
# OS：alpine
FROM alpine:latest

# 作者
MAINTAINER Niuren.Zhu "niuren.zhu@icloud.com"

# 安装工具
RUN set -x \
    # 更新源
    && apk update \
    # 安装解压、网络请求
    && apk add --no-cache unzip curl wget vim \
    # 删除源
    && rm -rf /var/cache/apk/*

# 环境变量-ibas目录
ENV IBAS_HOME=/usr/share/ibas
# 创建数据文件夹
RUN set -x \
    && mkdir -p ${IBAS_HOME}

# 设置工作目录
WORKDIR ${IBAS_HOME}