apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv-nas
  labels:
    alicloud-pvname: wordpress-pv-nas
spec:
  capacity:
    storage: 20Gi
  storageClassName: nas
  accessModes:
    - ReadWriteMany
  flexVolume:
    driver: "alicloud/nas"
    options:
      server: "168fb49513-fkq54.cn-beijing.nas.aliyuncs.com"
      path: "/wordpress"
      vers: "4.0"