apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
  namespace: default
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nas
  resources:
    requests:
      # CHANGE ME
      storage: 20Gi