apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: c01-01-deploy
  namespace: customer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: c01-01-deploy
    spec:
      imagePullSecrets:
      - name: registry-key
      containers:
      - name: c01-01-tomcat
        image: docker.avacloud.com.cn/colorcoding/tomcat:201807011633
        ports:
        - containerPort: 8080
        resources:
         limits:
          cpu: 300m
          memory: 512Mi
         requests:
          cpu: 150m
          memory: 512Mi
        env:
        - name: JAVA_OPTS
          value: "-Xmx512m"
        volumeMounts:
        - mountPath: /etc/localtime
          name: time
        - mountPath: /usr/local/tomcat/ibas/
          name: ibas
      - name: c01-01-web
        image: docker.avacloud.com.cn/colorcoding/nginx:201807011633
        ports:
        - containerPort: 80
        resources:
         limits:
          cpu: 100m
          memory: 64Mi
         requests:
          cpu: 100m
          memory: 32Mi
        volumeMounts:
        - mountPath: /etc/localtime
          name: time
      - name: c01-01-data
        image: docker.avacloud.com.cn/colorcoding/data:ibas-alpine
        resources:
         limits:
          cpu: 100m
          memory: 64Mi
         requests:
          cpu: 100m
          memory: 32Mi
        volumeMounts:
        - mountPath: /etc/localtime
          name: time
        - mountPath: /usr/share/ibas/
          name: ibas
      volumes:
       - name: time
         hostPath:
          path: /etc/localtime
       - name: ibas
         hostPath:
          path: /mnt/customers/c01-01/ibas/
      nodeSelector:
        group: customer
---
apiVersion: v1
kind: Service
metadata:
 name: c01-01-web
 namespace: customer
 labels:
   name: c01-01-web
spec:
 ports:
 - port: 80
   targetPort: 80
 selector:
  app: c01-01-deploy
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: c01-01-ingress
  namespace: customer #服务在哪个空间内就写哪个空间
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-read-timeout: '3000'
    nginx.ingress.kubernetes.io/proxy-connect-timeout: '1200'
    ingress.kubernetes.io/client-body-buffer-size: 200m
    nginx.ingress.kubernetes.io/proxy-send-timeout: '2400'
    nginx.ingress.kubernetes.io/keepalive-timeout: '300'
    nginx.ingress.kubernetes.io/proxy-body-size: 200m
    nginx.ingress.kubernetes.io/from-to-www-redirect: 'true'
spec:
  tls:
    - hosts:
        - app.avacloud.com.cn
      secretName: app-tls
  rules:
  - host: app.avacloud.com.cn   #此service的访问域名
    http:
      paths:
      - backend:
          serviceName: c01-01-web
          servicePort: 80
        path: /c01/i01/
status:
  loadBalancer:
    ingress:
      - ip: 47.95.97.32 #负载均衡SLB IP
