apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ibas-platform-deploy
  namespace: ibas-platform
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ibas-platform-deploy
    spec:
      containers:
      - name: ibas-platform-tomcat
        image: docker.avacloud.com.cn/colorcoding/tomcat:ibas-platform
        ports:
        - containerPort: 8080
        resources:
         limits:
          cpu: 300m
          memory: 768Mi
         requests: 
          cpu: 150m
          memory: 512Mi
        env:
        - name: JAVA_OPTS
          value: "-Xmx512m"
        command: ["/bin/sh"]
        args: ["/usr/local/tomcat/initialize_apps.sh"]
        volumeMounts:
        - mountPath: /etc/localtime
          name: time
        - mountPath: /usr/local/tomcat/ibas/
          name: ibas
      - name: ibas-platform-web
        image: docker.avacloud.com.cn/colorcoding/nginx:ibas-platform
        ports:
        - containerPort: 80
        resources:
         limits:
          cpu: 200m
          memory: 128Mi
         requests:
          cpu: 150m
          memory: 64Mi
        volumeMounts:
        - mountPath: /etc/localtime
          name: time
      - name: ibas-platform-data
        image: docker.avacloud.com.cn/colorcoding/data:ibas-alpine
        resources:
         limits:
          cpu: 100m
          memory: 64Mi
         requests:
          cpu: 50m
          memory: 32Mi
        volumeMounts:
        - mountPath: /etc/localtime
          name: time
        - mountPath: /usr/share/ibas/
          name: ibas
      volumes:
       - name: time
         hostPath:
          path: /etc/localtime
       - name: ibas
         hostPath:
          path: /mnt/customers/ibas-platform/ibas/
      nodeSelector:
        group: platform
---
apiVersion: v1
kind: Service
metadata:
 name: ibas-platform-svc
 namespace: ibas-platform
 labels:
   name: ibas-platform-svc
spec:
 ports:
 - port: 80
   targetPort: 80
 selector:
  app: ibas-platform-deploy
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ibas-platform-ingress
  namespace: ibas-platform #服务在哪个空间内就写哪个空间
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-read-timeout: '3000'
    nginx.ingress.kubernetes.io/proxy-connect-timeout: '1200'
    ingress.kubernetes.io/client-body-buffer-size: 200m
    nginx.ingress.kubernetes.io/proxy-send-timeout: '2400'
    nginx.ingress.kubernetes.io/keepalive-timeout: '300'
    nginx.ingress.kubernetes.io/proxy-body-size: 200m
    nginx.ingress.kubernetes.io/from-to-www-redirect: 'true'
spec:
  tls:
    - hosts:
        - console.avacloud.com.cn
      secretName: console-tls
  rules:
  - host: console.avacloud.com.cn   #此service的访问域名
    http:
      paths:
      - backend:
          serviceName: ibas-platform-svc 
          servicePort: 80
status:
  loadBalancer:
    ingress:
      - ip: 47.95.97.32 #负载均衡SLB IP
          