apiVersion: v1
kind: Namespace
metadata:
   name: deploy
   labels:
     name: deploy
---
apiVersion: v1
kind: Namespace
metadata:
   name: console
   labels:
     name: console
---
apiVersion: v1
kind: Namespace
metadata:
   name: customer
   labels:
     name: customer