apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-pvc
  namespace: nexus
  labels:
    app: nexus
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nas
  resources:
    requests:
      # CHANGE ME
      storage: 50Gi